// Inner page copy, English and Nepali. Facts only from website/docs/facts.md.
// Text in [square brackets] is not yet known; the page shows it as a gap for the school to fill.
import type { Lang } from '../content';

const en = {
  tbcNote: 'To be confirmed by the school',
  about: {
    title: 'Our story.', other: 'हाम्रो कथा।',
    intro: 'Since 2059 BS, families in Hetauda have walked their children up to our yellow-and-blue building in Chisapani. This is how we got here, and who is waiting inside.',
    milestonesTitle: 'Since 2059.',
    milestones: [
      ['2059 BS', 'The school opens in Hetauda-4, Chisapani.', null],
      ['[Year]', 'The four-floor building with blue balconies. [When it was built]', 'building'],
      ['[Year]', 'Our first SEE batch. [Year and results]', null],
      ['2079 BS', 'Farewell for the Class 10 batch, with the whole school there to see them off.', 'farewell'],
      ['Every year', 'The Class 10 trip to Chitlang and Chandragiri.', 'himal'],
      ['Recent', 'A 3.96 GPA, honoured by the Ward No. 4 Office.', 'gpa'],
    ] as [string, string, string | null][],
    principalTitle: 'A word from the principal.',
    principal: "[The principal's message to families, in their own words]",
    principalName: "[Principal's name]",
    daysTitle: 'What you will see on any school day.',
    days: [
      ['cls2', 'Two languages, every day', 'Lessons in English with Nepali alongside: reading the newspaper and writing about it.'],
      ['rice', 'Learning outside', 'Planting rice on Asar 15, and trips to Chitlang and Chandragiri.'],
      ['dance', 'Our own culture', 'Teej and Janmashtami dances, and cultural programmes on stage.'],
      ['ashram', 'Giving back', 'Students visiting Manav Sewa Ashram.'],
    ] as [string, string, string][],
    peopleTitle: 'The people inside the gate.',
    people: '[Number of teachers and staff]. The teachers and staff of Satyam Xavier\'s, photographed in front of the school.',
    // Storyline v4: the About page is the teacher's book, told in chapters.
    chapters: ['Since 2059.', 'One building, thirteen classes.', 'The people inside the gate.', 'What we are proud of.', 'What we believe.'],
    building: 'Every class from Nursery to Class 10 is in one building: four floors, yellow walls, blue balconies, open corridors along the front. On the cover photos, students line every balcony.',
    buildingFacts: [['Classes', 'Nursery, LKG, UKG and Class 1 to 10'], ['Floors', 'Four, with open corridors'], ['Where', 'Hetauda-4, Chisapani'], ['Since', '2059 BS [to confirm]']] as [string, string][],
    proud: [
      ['gpa', 'A 3.96 GPA', 'One of our students scored a 3.96 GPA and was honoured by the Ward No. 4 Office, Hetauda. [Which exam]'],
      ['cert', 'District level, at four and five', 'Our LKG and UKG children were selected for the district-level drawing and colouring competition.'],
      ['medal3', 'Province level', 'One of our students went on to the province-level drawing competition. [Name, with the family\'s permission]'],
      ['medal2', 'Medal days', 'Certificates and medals, class by class, for every competition the school takes part in.'],
    ] as [string, string, string][],
    motto: '[The school motto, in English and Nepali]',
  },
  academics: {
    title: 'Nursery to Class 10, one school.', other: 'नर्सरीदेखि कक्षा १० सम्म, एउटै विद्यालय।',
    intro: 'Thirteen classes in four stages. Each stage shows what children learn and how they are taught.',
    learnLabel: 'What they learn', howLabel: 'How they are taught',
    stages: [
      ['Early years', 'Nursery, LKG and UKG. Ages 3 to 5.', 'Small hands, first letters.', '[Subjects and routine for the early years]', "Colour, paper and song. Father's Day cards cut and folded by hand, birthdays celebrated in class, and LKG and UKG picked for the district-level drawing competition.", ['ey5', 'birthday']],
      ['Primary', 'Class 1 to 5.', 'Reading the world.', '[Subjects for Class 1 to 5]', 'On newspaper day the class reads The Kathmandu Post together and writes its own stories. Medals and certificates for every competition.', ['write1', 'medal2']],
      ['Lower secondary', 'Class 6 to 8.', 'Going deeper.', '[Subjects for Class 6 to 8]', 'Group work on the classroom floor, projects for the activity-based school exhibition, and the first turns at leading.', ['cls4', 'cls5']],
      ['Secondary', 'Class 9 and 10.', 'Ready for the SEE.', '[SEE subjects and optional subjects]', 'Two years of steady preparation, the Class 10 trip to Chandragiri, and a farewell the whole school turns out for. One of our students was honoured for a 3.96 GPA.', ['batch', 'heart']],
    ] as [string, string, string, string, string, [string, string]][],
    dayTitle: 'A school day.',
    day: ['Gate opens', 'Morning assembly', 'Lessons', 'Tiffin', 'Lessons and activities', 'Home time'],
    dayTime: '[time]',
    appTitle: 'Every term, on your phone.',
    app: 'Terminal exam marks, report cards, attendance and homework appear in the school app as soon as teachers publish them, in English or Nepali.',
  },
  gallery: {
    title: 'School life, in photos.', other: 'तस्बिरमा विद्यालय जीवन।',
    intro: 'Every photo here was posted by the school on its own page. Pick an album, or see them all.',
    all: 'All photos', close: 'Close', prev: 'Previous photo', next: 'Next photo', of: 'of',
    consent: '[Families\' consent to show these photos online]',
    albums: [
      ['newspaper', 'Newspaper day', 'The Kathmandu Post spread across the floor, and stories written beside it.', ['cls1', 'cls2', 'cls3', 'cls4', 'cls5', 'cls6', 'write1', 'write2']],
      ['cards', "Father's Day cards", 'Shirts and bow ties, cut and folded by our youngest.', ['ey1', 'ey2', 'ey3', 'ey4', 'ey5']],
      ['asar', 'Asar 15', 'Planting rice in a flooded field on National Paddy Day.', ['rice', 'rice2']],
      ['trip', 'Class 10 trip', 'Chitlang and Chandragiri, with the Himalaya behind.', ['himal', 'boat', 'tripbus', 'outing', 'heart', 'dalbhat']],
      ['stage', 'On stage', 'Teej, cultural programmes, prize days and the farewell.', ['dance', 'celebrate', 'award', 'farewell']],
      ['proud', 'Medals and honours', 'Competition medals, certificates and the 3.96 GPA.', ['medal', 'medal2', 'medal3', 'cert', 'gpa']],
      ['service', 'Giving back', 'Our visit to Manav Sewa Ashram.', ['ashram']],
      ['school', 'Our school and people', 'The building, the teachers and staff, and the whole school together.', ['building', 'hero', 'staff', 'teachers', 'batch', 'lawn', 'gateevent', 'birthday']],
    ] as [string, string, string, string[]][],
  },
  life: {
    title: 'School life.', other: 'विद्यालय जीवन।',
    intro: 'Festivals, competitions, trips and service, all through the year. Every photo here was posted by the school.',
    yearTitle: 'Our year, month by month.',
    months: [
      ['Baisakh', '[New session begins]'], ['Jestha', ''], ['Asar', 'Asar 15, rice planting'], ['Shrawan', ''],
      ['Bhadra', 'Teej and Krishna Janmashtami'], ['Ashwin', '[Dashain holidays]'], ['Kartik', '[Tihar holidays]'], ['Mangsir', ''],
      ['Poush', '[Class 10 trip]'], ['Magh', '[School exhibition]'], ['Falgun', ''], ['Chaitra', '[Farewell and final exams]'],
    ] as [string, string][],
    activitiesTitle: 'Something for every child.',
    activities: [
      ['Drawing and colouring', 'LKG and UKG went to the district-level competition, and one student to the province level.'],
      ['Dance', 'Teej, Janmashtami and stage programmes.'],
      ['Competitions', 'Certificates and medals, class by class.'],
      ['Exhibition', 'The activity-based school exhibition.'],
      ['Service', 'Visits to Manav Sewa Ashram.'],
      ['Trips', 'The Class 10 trip to Chitlang and Chandragiri.'],
      ['Music', '[Music lessons]'],
      ['Sports', '[Sports offered]'],
    ] as [string, string][],
    galleryTitle: 'From our page.',
  },
  admissions: {
    title: 'Join us at the gate.', other: 'विद्यालयको ढोकामा स्वागत छ।',
    intro: 'Nursery to Class 10. Visit, call or write, and the office will walk you through the rest.',
    stepsTitle: 'How to join.',
    steps: [
      ['Visit or call', 'Come to Hetauda-4, Chisapani, or call 057-525563. [Office hours]'],
      ['Bring the documents', 'See the list below. [Entrance test or interview for some classes]'],
      ['Your child joins', 'Meet the class teacher, collect the uniform list, and sign in to the parent app.'],
    ] as [string, string][],
    docsTitle: 'Documents to bring.', docsNote: 'A draft list. The school office confirms the final one.',
    docs: ['Birth certificate (जन्मदर्ता)', "The previous school's record or transfer certificate", 'Report card from the last class', 'Passport-size photos of the child [how many]', "A parent or guardian's citizenship copy [to be confirmed]"],
    agesTitle: 'Which class for my child?', agesNote: 'Usual ages. [The school confirms the cut-off]',
    ages: [['Nursery', '3+'], ['LKG', '4+'], ['UKG', '5+'], ['Class 1', '6+'], ['Class 2 to 10', 'by the last class passed']] as [string, string][],
    feesTitle: 'Fees and scholarships.', fees: '[Published fees, a range, or on enquiry: the school decides]', feesApp: 'Once your child joins, fees and receipts are in the parent app too.',
    faqTitle: 'Questions families ask.',
    faq: [
      ['How will I know how my child is doing?', "Attendance, marks, homework, fees and notices are in the school's parent app, in English or Nepali. You get a login when your child joins."],
      ['What are the school hours?', '[School hours]'],
      ['Is there school transport?', '[Routes and fees]'],
      ['Do you have boarding?', '[Boarding]'],
      ['What language are lessons in?', '[English medium, with Nepali as a subject: to be confirmed]'],
      ['Can my child join in the middle of the year?', '[Mid-year admission]'],
    ] as [string, string][],
    reachTitle: 'Talk to the office.',
  },
  news: {
    title: "What's happening.", other: 'सूचना र समाचार।',
    intro: 'News and notices from the school. Notices the school posts in its app for everyone will appear here too.',
    items: [
      ['Achievement', '[Date]', 'Our young artist reaches the province level.', 'After LKG and UKG were selected at district level for drawing and colouring, one of our students has reached the province-level competition. [Name and photo with the family\'s permission]', null],
      ['Achievement', '[Date]', 'LKG and UKG selected at district level.', 'Our youngest were selected for the district-level drawing and colouring competition. [Photo from the competition]', null],
      ['Event', 'Bhadra 2083', 'A Teej dance by our students.', "Bringing Nepal's own festival to the stage. Happy Haritalika Teej to everyone.", null],
      ['Event', 'Bhadra 2083', 'Krishna Janmashtami with the little ones.', 'Our youngest dancers made the festival special.', null],
      ['Notice', '[Date]', 'Weather alert: red alert for 15 districts.', 'Shared from the Department of Hydrology and Meteorology. [Whether the school closed]', null],
      ['Achievement', '[Date]', 'A 3.96 GPA, honoured by Ward No. 4.', 'Our student was honoured by the Ward No. 4 Office, Hetauda.', 'gpa'],
    ] as [string, string, string, string, string | null][],
  },
  contact: {
    title: 'Come and say namaste.', other: 'हामीलाई भेट्न आउनुहोस्।',
    callTitle: 'Call the school', hours: 'Office hours: [to be confirmed]',
    emailTitle: 'Email', emailNote: 'The office replies on school days.',
    visitTitle: 'Visit', mapLink: 'Open in Google Maps',
    findTitle: 'Finding us.',
    find: [['From Hetauda bus park', '[Route and landmarks]'], ['Look for', 'The yellow building with blue balconies in Chisapani.'], ['Parking', '[Parking]']] as [string, string][],
  },
};

type Pages = typeof en;

const ne: Pages = {
  tbcNote: 'विद्यालयले पुष्टि गर्न बाँकी',
  about: {
    title: 'हाम्रो कथा।', other: 'Our story.',
    intro: 'वि.सं. २०५९ देखि हेटौंडाका परिवारले आफ्ना बच्चा चिसापानीको हाम्रो पहेँलो-निलो भवनसम्म पुर्‍याउँदै आएका छन्। हामी यहाँसम्म कसरी आइपुग्यौँ, र भित्र को पर्खिरहेका छन्, यहाँ छ।',
    milestonesTitle: '२०५९ देखि।',
    milestones: [
      ['वि.सं. २०५९', 'हेटौंडा-४, चिसापानीमा विद्यालय सुरु।', null],
      ['[वर्ष]', 'निलो बार्दली भएको चार तले भवन। [कहिले बन्यो]', 'building'],
      ['[वर्ष]', 'हाम्रो पहिलो SEE ब्याच। [वर्ष र नतिजा]', null],
      ['वि.सं. २०७९', 'कक्षा १० को बिदाइ, पूरै विद्यालयको उपस्थितिमा।', 'farewell'],
      ['हरेक वर्ष', 'चित्लाङ र चन्द्रागिरिमा कक्षा १० को भ्रमण।', 'himal'],
      ['हालै', '३.९६ GPA, वडा नं. ४ कार्यालयबाट सम्मानित।', 'gpa'],
    ],
    principalTitle: 'प्रधानाध्यापकको भनाइ।',
    principal: '[प्रधानाध्यापकको आफ्नै शब्दमा अभिभावकलाई सन्देश]',
    principalName: '[प्रधानाध्यापकको नाम]',
    daysTitle: 'कुनै पनि विद्यालय दिन यहाँ के देख्नुहुन्छ।',
    days: [
      ['cls2', 'हरेक दिन दुई भाषा', 'अंग्रेजीमा पढाइ, साथमा नेपाली: पत्रिका पढ्ने र त्यसबारे लेख्ने।'],
      ['rice', 'बाहिर सिकाइ', 'असार १५ मा धान रोपाइँ, चित्लाङ र चन्द्रागिरिको भ्रमण।'],
      ['dance', 'हाम्रै संस्कृति', 'तीज र जन्माष्टमीका नाच, मञ्चमा सांस्कृतिक कार्यक्रम।'],
      ['ashram', 'समाजलाई फर्काउँदै', 'मानव सेवा आश्रमको भ्रमण।'],
    ],
    peopleTitle: 'ढोकाभित्रका मानिस।',
    people: '[शिक्षक र कर्मचारीको सङ्ख्या]। विद्यालय अगाडि खिचिएको सत्यम जेभियर्सका शिक्षक र कर्मचारी।',
    chapters: ['२०५९ देखि।', 'एउटै भवन, तेह्र कक्षा।', 'ढोकाभित्रका मानिस।', 'हामीलाई गर्व लाग्ने कुरा।', 'हाम्रो विश्वास।'],
    building: 'नर्सरीदेखि कक्षा १० सम्मका सबै कक्षा एउटै भवनमा छन्: चार तला, पहेँला भित्ता, निला बार्दली, अगाडि खुला करिडोर। कभर फोटोमा हरेक बार्दलीमा विद्यार्थी लहरै उभिएका छन्।',
    buildingFacts: [['कक्षा', 'नर्सरी, LKG, UKG र कक्षा १ देखि १०'], ['तला', 'चार, खुला करिडोरसहित'], ['ठाउँ', 'हेटौंडा-४, चिसापानी'], ['स्थापना', 'वि.सं. २०५९ [पुष्टि गर्न बाँकी]']],
    proud: [
      ['gpa', '३.९६ GPA', 'हाम्रा एक विद्यार्थीले ३.९६ GPA ल्याई वडा नं. ४ कार्यालय, हेटौंडाबाट सम्मान पाए। [कुन परीक्षा]'],
      ['cert', 'चार-पाँच वर्षमै जिल्लास्तर', 'हाम्रा LKG र UKG का नानीहरू जिल्लास्तरीय चित्रकला तथा रङ भराइ प्रतियोगितामा छनोट भए।'],
      ['medal3', 'प्रदेशस्तर', 'हाम्रा एक विद्यार्थी प्रदेशस्तरीय चित्रकला प्रतियोगितासम्म पुगे। [परिवारको अनुमतिसहित नाम]'],
      ['medal2', 'पदक दिवस', 'विद्यालयले भाग लिने हरेक प्रतियोगितामा कक्षैपिच्छे प्रमाणपत्र र पदक।'],
    ],
    motto: '[विद्यालयको आदर्श वाक्य, अंग्रेजी र नेपालीमा]',
  },
  academics: {
    title: 'नर्सरीदेखि कक्षा १० सम्म, एउटै विद्यालय।', other: 'Nursery to Class 10, one school.',
    intro: 'चार चरणमा तेह्र कक्षा। हरेक चरणमा बच्चाले के सिक्छन् र कसरी सिकाइन्छ, यहाँ छ।',
    learnLabel: 'के सिक्छन्', howLabel: 'कसरी सिकाइन्छ',
    stages: [
      ['प्रारम्भिक वर्ष', 'नर्सरी, LKG र UKG। ३ देखि ५ वर्ष।', 'साना हात, पहिलो अक्षर।', '[प्रारम्भिक कक्षाका विषय र दिनचर्या]', 'रङ, कागज र गीत। हातले काटेर पट्याएका बुबा दिवसका कार्ड, कक्षामै जन्मदिन, र जिल्लास्तरीय चित्रकला प्रतियोगितामा छनोट भएका LKG र UKG।', ['ey5', 'birthday']],
      ['प्राथमिक', 'कक्षा १ देखि ५।', 'संसार पढ्दै।', '[कक्षा १ देखि ५ का विषय]', 'पत्रिका दिवसमा कक्षाले सँगै द काठमाडौं पोस्ट पढ्छ र आफ्नै कथा लेख्छ। हरेक प्रतियोगितामा पदक र प्रमाणपत्र।', ['write1', 'medal2']],
      ['निम्न माध्यमिक', 'कक्षा ६ देखि ८।', 'अझ गहिराइमा।', '[कक्षा ६ देखि ८ का विषय]', 'कक्षाको भुइँमा समूह कार्य, क्रियाकलापमा आधारित विद्यालय प्रदर्शनीका परियोजना, र नेतृत्वका पहिला अवसर।', ['cls4', 'cls5']],
      ['माध्यमिक', 'कक्षा ९ र १०।', 'SEE को तयारी।', '[SEE का विषय र ऐच्छिक विषय]', 'दुई वर्षको निरन्तर तयारी, चन्द्रागिरिको भ्रमण, र पूरै विद्यालय जुट्ने बिदाइ। हाम्रा एक विद्यार्थी ३.९६ GPA का लागि सम्मानित भए।', ['batch', 'heart']],
    ],
    dayTitle: 'विद्यालयको एक दिन।',
    day: ['ढोका खुल्छ', 'बिहानको प्रार्थना', 'पढाइ', 'खाजा', 'पढाइ र क्रियाकलाप', 'घर फर्किने समय'],
    dayTime: '[समय]',
    appTitle: 'हरेक त्रैमासिक, तपाईंको फोनमा।',
    app: 'त्रैमासिक परीक्षाका अङ्क, प्रगति-पत्र, हाजिरी र गृहकार्य शिक्षकले प्रकाशित गर्नेबित्तिकै विद्यालयको एपमा देखिन्छन्, अंग्रेजी वा नेपालीमा।',
  },
  gallery: {
    title: 'तस्बिरमा विद्यालय जीवन।', other: 'School life, in photos.',
    intro: 'यहाँका सबै तस्बिर विद्यालयले आफ्नै पेजमा राखेका हुन्। एउटा एल्बम छान्नुहोस्, वा सबै हेर्नुहोस्।',
    all: 'सबै तस्बिर', close: 'बन्द गर्नुहोस्', prev: 'अघिल्लो तस्बिर', next: 'अर्को तस्बिर', of: 'मध्ये',
    consent: '[यी तस्बिर अनलाइन देखाउन परिवारको अनुमति]',
    albums: [
      ['newspaper', 'पत्रिका दिवस', 'भुइँभरि फिँजाइएको द काठमाडौं पोस्ट, र छेउमै लेखिएका कथा।', ['cls1', 'cls2', 'cls3', 'cls4', 'cls5', 'cls6', 'write1', 'write2']],
      ['cards', 'बुबा दिवसका कार्ड', 'साना नानीहरूले काटेर पट्याएका सर्ट र बो-टाई।', ['ey1', 'ey2', 'ey3', 'ey4', 'ey5']],
      ['asar', 'असार १५', 'राष्ट्रिय धान दिवसमा हिलो खेतमा धान रोपाइँ।', ['rice', 'rice2']],
      ['trip', 'कक्षा १० को भ्रमण', 'चित्लाङ र चन्द्रागिरि, पछाडि हिमाल।', ['himal', 'boat', 'tripbus', 'outing', 'heart', 'dalbhat']],
      ['stage', 'मञ्चमा', 'तीज, सांस्कृतिक कार्यक्रम, पुरस्कार दिवस र बिदाइ।', ['dance', 'celebrate', 'award', 'farewell']],
      ['proud', 'पदक र सम्मान', 'प्रतियोगिताका पदक, प्रमाणपत्र र ३.९६ GPA।', ['medal', 'medal2', 'medal3', 'cert', 'gpa']],
      ['service', 'समाजलाई फर्काउँदै', 'मानव सेवा आश्रमको भ्रमण।', ['ashram']],
      ['school', 'हाम्रो विद्यालय र मानिस', 'भवन, शिक्षक र कर्मचारी, र पूरै विद्यालय सँगै।', ['building', 'hero', 'staff', 'teachers', 'batch', 'lawn', 'gateevent', 'birthday']],
    ],
  },
  life: {
    title: 'विद्यालय जीवन।', other: 'School life.',
    intro: 'वर्षभरि चाडपर्व, प्रतियोगिता, भ्रमण र सेवा। यहाँका सबै फोटो विद्यालयले नै पोस्ट गरेका हुन्।',
    yearTitle: 'हाम्रो वर्ष, महिनैपिच्छे।',
    months: [
      ['बैशाख', '[नयाँ सत्र सुरु]'], ['जेठ', ''], ['असार', 'असार १५, धान रोपाइँ'], ['साउन', ''],
      ['भदौ', 'तीज र कृष्ण जन्माष्टमी'], ['असोज', '[दशैँ बिदा]'], ['कात्तिक', '[तिहार बिदा]'], ['मंसिर', ''],
      ['पुस', '[कक्षा १० को भ्रमण]'], ['माघ', '[विद्यालय प्रदर्शनी]'], ['फागुन', ''], ['चैत', '[बिदाइ र वार्षिक परीक्षा]'],
    ],
    activitiesTitle: 'हरेक बच्चाका लागि केही न केही।',
    activities: [
      ['चित्रकला र रङ भराइ', 'LKG र UKG जिल्लास्तरीय प्रतियोगितामा, र एक विद्यार्थी प्रदेशस्तरसम्म।'],
      ['नाच', 'तीज, जन्माष्टमी र मञ्च कार्यक्रम।'],
      ['प्रतियोगिता', 'कक्षैपिच्छे प्रमाणपत्र र पदक।'],
      ['प्रदर्शनी', 'क्रियाकलापमा आधारित विद्यालय प्रदर्शनी।'],
      ['सेवा', 'मानव सेवा आश्रमको भ्रमण।'],
      ['भ्रमण', 'चित्लाङ र चन्द्रागिरिमा कक्षा १० को भ्रमण।'],
      ['सङ्गीत', '[सङ्गीत कक्षा]'],
      ['खेलकुद', '[खेलकुदका विधा]'],
    ],
    galleryTitle: 'हाम्रो पेजबाट।',
  },
  admissions: {
    title: 'विद्यालयको ढोकामा स्वागत छ।', other: 'Join us at the gate.',
    intro: 'नर्सरीदेखि कक्षा १० सम्म। आउनुहोस्, फोन गर्नुहोस् वा लेख्नुहोस्, बाँकी कार्यालयले बुझाउँछ।',
    stepsTitle: 'कसरी भर्ना हुने।',
    steps: [
      ['आउनुहोस् वा फोन गर्नुहोस्', 'हेटौंडा-४, चिसापानी आउनुहोस्, वा 057-525563 मा फोन गर्नुहोस्। [कार्यालय समय]'],
      ['कागजात ल्याउनुहोस्', 'तलको सूची हेर्नुहोस्। [केही कक्षामा प्रवेश परीक्षा वा अन्तर्वार्ता]'],
      ['बच्चा भर्ना हुन्छ', 'कक्षा शिक्षकलाई भेट्नुहोस्, पोसाकको सूची लिनुहोस्, र अभिभावक एपमा लगइन गर्नुहोस्।'],
    ],
    docsTitle: 'ल्याउनुपर्ने कागजात।', docsNote: 'मस्यौदा सूची। अन्तिम सूची विद्यालयको कार्यालयले पुष्टि गर्छ।',
    docs: ['जन्मदर्ता प्रमाणपत्र', 'अघिल्लो विद्यालयको रेकर्ड वा स्थानान्तरण प्रमाणपत्र', 'अघिल्लो कक्षाको प्रगति-पत्र', 'बच्चाको पासपोर्ट साइजको फोटो [कति वटा]', 'अभिभावकको नागरिकताको प्रतिलिपि [पुष्टि हुन बाँकी]'],
    agesTitle: 'मेरो बच्चा कुन कक्षामा?', agesNote: 'सामान्य उमेर। [उमेर सीमा विद्यालयले पुष्टि गर्छ]',
    ages: [['नर्सरी', '३+'], ['LKG', '४+'], ['UKG', '५+'], ['कक्षा १', '६+'], ['कक्षा २ देखि १०', 'उत्तीर्ण कक्षाअनुसार']],
    feesTitle: 'शुल्क र छात्रवृत्ति।', fees: '[प्रकाशित शुल्क, दायरा, वा सोधपुछमा: विद्यालयको निर्णय]', feesApp: 'बच्चा भर्ना भएपछि शुल्क र रसिद अभिभावक एपमा पनि हुन्छन्।',
    faqTitle: 'अभिभावकले सोध्ने प्रश्न।',
    faq: [
      ['मेरो बच्चाको पढाइ कस्तो छ, कसरी थाहा पाउने?', 'हाजिरी, अङ्क, गृहकार्य, शुल्क र सूचना विद्यालयको अभिभावक एपमा अंग्रेजी वा नेपालीमा हुन्छन्। बच्चा भर्ना भएपछि तपाईंले लगइन पाउनुहुन्छ।'],
      ['विद्यालय समय कति हो?', '[विद्यालय समय]'],
      ['विद्यालयको यातायात छ?', '[रुट र शुल्क]'],
      ['छात्रावास छ?', '[छात्रावास]'],
      ['पढाइ कुन भाषामा हुन्छ?', '[अंग्रेजी माध्यम, नेपाली विषयसहित: पुष्टि हुन बाँकी]'],
      ['वर्षको बीचमा भर्ना हुन मिल्छ?', '[वर्षको बीचमा भर्ना]'],
    ],
    reachTitle: 'कार्यालयसँग कुरा गर्नुहोस्।',
  },
  news: {
    title: 'के भइरहेको छ।', other: "What's happening.",
    intro: 'विद्यालयका समाचार र सूचना। विद्यालयले एपमा सबैका लागि राखेका सूचना पनि यहाँ देखिनेछन्।',
    items: [
      ['उपलब्धि', '[मिति]', 'हाम्रा सानो कलाकार प्रदेशस्तरसम्म।', 'LKG र UKG जिल्लास्तरमा छनोट भएपछि हाम्रा एक विद्यार्थी प्रदेशस्तरीय प्रतियोगितासम्म पुगे। [परिवारको अनुमतिसहित नाम र फोटो]', null],
      ['उपलब्धि', '[मिति]', 'LKG र UKG जिल्लास्तरमा छनोट।', 'हाम्रा साना नानीहरू जिल्लास्तरीय चित्रकला तथा रङ भर्ने प्रतियोगितामा छनोट भए। [प्रतियोगिताको फोटो]', null],
      ['कार्यक्रम', 'भदौ २०८३', 'विद्यार्थीको तीज नाच।', 'नेपालको आफ्नै पर्व मञ्चमा। सबैमा हरितालिका तीजको शुभकामना।', null],
      ['कार्यक्रम', 'भदौ २०८३', 'साना नानीहरूसँग कृष्ण जन्माष्टमी।', 'हाम्रा साना नर्तकले पर्वलाई विशेष बनाए।', null],
      ['सूचना', '[मिति]', 'मौसम चेतावनी: १५ जिल्लामा रेड अलर्ट।', 'जल तथा मौसम विज्ञान विभागबाट साझा गरिएको। [विद्यालय बन्द भयो कि भएन]', null],
      ['उपलब्धि', '[मिति]', '३.९६ GPA, वडा नं. ४ बाट सम्मानित।', 'हाम्रा विद्यार्थी वडा नं. ४ कार्यालय, हेटौंडाबाट सम्मानित भए।', 'gpa'],
    ],
  },
  contact: {
    title: 'हामीलाई भेट्न आउनुहोस्।', other: 'Come and say namaste.',
    callTitle: 'विद्यालयलाई फोन', hours: 'कार्यालय समय: [पुष्टि हुन बाँकी]',
    emailTitle: 'इमेल', emailNote: 'कार्यालयले विद्यालय दिनमा जवाफ दिन्छ।',
    visitTitle: 'भेट्न आउनुहोस्', mapLink: 'गुगल नक्सामा खोल्नुहोस्',
    findTitle: 'हामीलाई कसरी भेट्ने।',
    find: [['हेटौंडा बसपार्कबाट', '[बाटो र चिनारी]'], ['यो खोज्नुहोस्', 'चिसापानीमा निलो बार्दली भएको पहेँलो भवन।'], ['पार्किङ', '[पार्किङ]']],
  },
};

export const pages: Record<Lang, Pages> = { en, ne };
